package me.adamix.sonoran.cad;

import alpine.json.codec.Codec;
import lombok.Builder;
import me.adamix.sonoran.cad.data.CADAccount;
import me.adamix.sonoran.cad.data.CADCharacter;
import me.adamix.sonoran.cad.request.general.GetVersionResponse;
import me.adamix.sonoran.http.SonoranHttpService;
import me.adamix.sonoran.http.SonoranRequest;
import me.adamix.sonoran.http.SonoranRequestService;
import me.adamix.sonoran.http.annotation.Methods;
import me.adamix.sonoran.http.param.Params;
import me.adamix.sonoran.SonoranURL;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

@Builder(builderClassName = "Builder")
public class SonoranCadClient {
    private final @NotNull SonoranRequestService requestService;
    private final @NotNull String apiKey;
    private final @NotNull String communityId;
    private final @NotNull String baseUrl;

    // Rest of the fields are generated by lombok
    public static class Builder {
        private SonoranRequestService requestService = null;

        public Builder baseUrl(@NotNull SonoranURL url) {
            this.baseUrl = url.getUrl();
            return this;
        }

        private SonoranRequestService createService() {
            return new SonoranRequestService(
                    new SonoranHttpService(),
                    baseUrl,
                    Map.of(
                            "Authorization", "Bearer %s".formatted(apiKey),
                            "Accept", "application/json"
                    )
            );
        }

        public SonoranCadClient build() {
            if (this.requestService == null) {
                this.requestService = createService();
            }
            return new SonoranCadClient(requestService, apiKey, communityId, baseUrl);
        }
    }

    @ApiStatus.Internal
    public <T> @NotNull CompletableFuture<T> sendRequest(
            @NotNull SonoranRequest request,
            @NotNull Params params,
            @NotNull Codec<T> codec
    ) {
        return requestService.sendRequest(request, params, codec);
    }

    public @NotNull CompletableFuture<GetVersionResponse> getVersion() {
        return requestService.sendRequest(Methods.GET_VERSION, Params.empty(), GetVersionResponse.CODEC);
    }

    public @NotNull CompletableFuture<List<CADCharacter>> getCharactersByCommunityId(@NotNull String communityUserId) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("communityUserId", communityUserId), CADCharacter.CODEC.list());
    }

    public @NotNull CompletableFuture<List<CADCharacter>> geCharactersByRoblox(@NotNull String roblox) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("roblox", roblox), CADCharacter.CODEC.list());
    }

    public @NotNull CompletableFuture<List<CADCharacter>> geCharactersByAccountUuid(@NotNull UUID accountUuid) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("accountUuid", accountUuid), CADCharacter.CODEC.list());
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByUsername(@NotNull String username) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("username", username), CADAccount.CODEC);
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByRoblox(@NotNull String robloxId) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("roblox", robloxId), CADAccount.CODEC);
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByUuid(@NotNull UUID uuid) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("accountUuid", uuid), CADAccount.CODEC);
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByCommunityId(@NotNull String communityUserId) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("communityUserId", communityUserId), CADAccount.CODEC);
    }

//
//    public @NotNull CompletableFuture<HeartBeatResponse> heartbeat(int serverId) {
//        return requestService.sendRequest(new HeartBeatRequest(serverId), HeartBeatResponse.CODEC);
//    }
}
