package me.adamix.sonoran.cad;

import lombok.Builder;
import me.adamix.sonoran.cad.data.CADCharacter;
import me.adamix.sonoran.cad.request.general.GetVersionResponse;
import me.adamix.sonoran.http.SonoranHttpService;
import me.adamix.sonoran.http.SonoranRequestService;
import me.adamix.sonoran.http.annotation.Methods;
import me.adamix.sonoran.http.param.Params;
import me.adamix.sonoran.SonoranURL;
import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

@Builder(builderClassName = "Builder")
public class SonoranCadClient {
    private final @NotNull SonoranRequestService requestService;
    private final @NotNull String apiKey;
    private final @NotNull String communityId;
    private final @NotNull String baseUrl;

    // Rest of the fields are generated by lombok
    public static class Builder {
        private SonoranRequestService requestService = null;

        public Builder baseUrl(@NotNull SonoranURL url) {
            this.baseUrl = url.getUrl();
            return this;
        }

        private SonoranRequestService createService() {
            return new SonoranRequestService(
                    new SonoranHttpService(),
                    baseUrl,
                    Map.of(
                            "Authorization", "Bearer %s".formatted(apiKey),
                            "Accept", "application/json"
                    )
            );
        }

        public SonoranCadClient build() {
            if (this.requestService == null) {
                this.requestService = createService();
            }
            return new SonoranCadClient(requestService, apiKey, communityId, baseUrl);
        }
    }

    public @NotNull CompletableFuture<GetVersionResponse> getVersion() {
        return requestService.sendRequest(Methods.GET_VERSION, Params.empty(), GetVersionResponse.CODEC);
    }

    public @NotNull CompletableFuture<List<CADCharacter>> getCharacters(@NotNull String communityUserId) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("communityUserId", communityUserId), CADCharacter.CODEC.list());
    }
//
//    public @NotNull CompletableFuture<HeartBeatResponse> heartbeat(int serverId) {
//        return requestService.sendRequest(new HeartBeatRequest(serverId), HeartBeatResponse.CODEC);
//    }
}