package me.adamix.sonoran.cad;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import lombok.Builder;
import me.adamix.sonoran.SonoranURL;
import me.adamix.sonoran.cad.data.CADAccount;
import me.adamix.sonoran.cad.data.CADCharacter;
import me.adamix.sonoran.cad.request.general.accounts.CreateCommunityLinkResponse;
import me.adamix.sonoran.cad.request.general.accounts.GetAccountsResponse;
import me.adamix.sonoran.cad.request.general.configuration.GetInfoRequest;
import me.adamix.sonoran.cad.request.general.configuration.GetInfoResponse;
import me.adamix.sonoran.cad.request.general.configuration.GetVersionResponse;
import me.adamix.sonoran.cad.request.general.records.UpdateRecordResponse;
import me.adamix.sonoran.http.SonoranHttpService;
import me.adamix.sonoran.http.SonoranRequest;
import me.adamix.sonoran.http.SonoranRequestService;
import me.adamix.sonoran.http.annotation.Methods;
import me.adamix.sonoran.http.param.Params;
import me.adamix.sonoran.json.TypeAdapters;
import org.jetbrains.annotations.ApiStatus;
import org.jetbrains.annotations.NotNull;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

@Builder(builderClassName = "Builder")
public class SonoranCadClient {
    private final @NotNull SonoranRequestService requestService;
    private final @NotNull String apiKey;
    private final @NotNull String communityId;
    private final @NotNull String baseUrl;
    private final Gson gson;

    // Rest of the fields are generated by lombok
    public static class Builder {
        private SonoranRequestService requestService = null;
        private Gson gson = null;

        public Builder baseUrl(@NotNull SonoranURL url) {
            this.baseUrl = url.getUrl();
            return this;
        }

        private SonoranRequestService createService() {
            return new SonoranRequestService(
                    gson,
                    new SonoranHttpService(),
                    baseUrl,
                    Map.of(
                            "Authorization", "Bearer %s".formatted(apiKey),
                            "Accept", "application/json",
                            "Content-Type", "application/json"
                    )
            );
        }

        private Gson createGson() {
            return new GsonBuilder()
                    .registerTypeAdapter(UUID.class, new TypeAdapters.UUIDAdapter())
                    .registerTypeAdapter(Instant.class, new TypeAdapters.InstantAdapter())
                    .registerTypeAdapter(CADAccount.Status.class, TypeAdapters.ordinal(CADAccount.Status.class))
                    .create();
        }

        public SonoranCadClient build() {
            if (gson == null) gson = createGson();
            if (this.requestService == null) {
                this.requestService = createService();
            }
            return new SonoranCadClient(
                    requestService,
                    apiKey,
                    communityId,
                    baseUrl,
                    gson
            );
        }
    }

    @ApiStatus.Internal
    public <T> @NotNull CompletableFuture<T> sendRequest(
            @NotNull SonoranRequest request,
            @NotNull Params params,
            @NotNull TypeToken<T> typeToken
    ) {
        return requestService.sendRequest(request, params, typeToken);
    }

    // ------------------------------
    //            Civilian
    // ------------------------------

    public @NotNull CompletableFuture<List<CADCharacter>> getCharactersByCommunityId(@NotNull String communityUserId) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("communityUserId", communityUserId), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<List<CADCharacter>> geCharactersByRoblox(@NotNull String roblox) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("roblox", roblox), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<List<CADCharacter>> geCharactersByAccountUuid(@NotNull UUID accountUuid) {
        return requestService.sendRequest(Methods.GET_CHARACTERS, Params.of("accountUuid", accountUuid), new TypeToken<>() {});
    }

    // ------------------------------
    //     General - Accounts
    // ------------------------------

    public @NotNull CompletableFuture<CreateCommunityLinkResponse> createCommunityLink(
            @NotNull String communityUserId
    ) {
        return requestService.sendRequest(Methods.CREATE_COMMUNITY_LINK, Params.of("communityUserId", communityUserId), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByUsername(@NotNull String username) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("username", username), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByRoblox(@NotNull String robloxId) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("roblox", robloxId), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByUuid(@NotNull UUID uuid) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("accountUuid", uuid), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<CADAccount> getAccountByCommunityId(@NotNull String communityUserId) {
        return requestService.sendRequest(Methods.GET_ACCOUNT, Params.of("communityUserId", communityUserId), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<GetAccountsResponse> getAccounts(
            @NotNull String username,
            int limit,
            int offset,
            int status
    ) {
        return requestService.sendRequest(
                Methods.GET_ACCOUNTS,
                Params.of(
                        "limit", limit,
                        "offset", offset,
                        "status", status,
                        "username", username
                ),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<GetAccountsResponse> getAccounts(
            @NotNull String username,
            int limit,
            int offset,
            @NotNull CADAccount.Status status
    ) {
        return getAccounts(username, limit, offset, status.ordinal());
    }

    // ------------------------------
    //     General - Configuration
    // ------------------------------

    public @NotNull CompletableFuture<GetVersionResponse> getVersion() {
        return requestService.sendRequest(Methods.GET_VERSION, Params.empty(), new TypeToken<>() {});
    }

    public @NotNull CompletableFuture<GetInfoResponse> getInfo() {
        return requestService.sendRequest(Methods.GET_INFO, Params.empty(), new TypeToken<>() {});
    }

    // ------------------------------
    //       General - Records
    // ------------------------------

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecord(
            int recordId,
            @NotNull Map<String, Object> record
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of("recordId", recordId, "record", record),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecord(
            int recordId,
            @NotNull String communityUserId,
            @NotNull Map<String, Object> record
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of("recordId", recordId, "communityUserId", communityUserId, "record", record),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordByRoblox(
            int recordId,
            @NotNull String roblox,
            @NotNull Map<String, Object> record
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of("recordId", recordId, "roblox", roblox, "record", record),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordByAccountUuid(
            int recordId,
            @NotNull UUID accountUuid,
            @NotNull Map<String, Object> record
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of("recordId", recordId, "accountUuid", accountUuid, "record", record),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordWithTemplate(
            int recordId,
            int templateId,
            @NotNull Map<String, Object> replaceValues
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of(
                        "recordId", recordId,
                        "templateId", templateId,
                        "useDictionary", true,
                        "replaceValues", replaceValues
                ),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordWithTemplate(
            int recordId,
            int templateId,
            @NotNull String communityUserId,
            @NotNull Map<String, Object> replaceValues
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of(
                        "recordId", recordId,
                        "templateId", templateId,
                        "useDictionary", true,
                        "communityUserId", communityUserId,
                        "replaceValues", replaceValues
                ),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordWithTemplateByRoblox(
            int recordId,
            int templateId,
            @NotNull String roblox,
            @NotNull Map<String, Object> replaceValues
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of(
                        "recordId", recordId,
                        "templateId", templateId,
                        "useDictionary", true,
                        "roblox", roblox,
                        "replaceValues", replaceValues
                ),
                new TypeToken<>() {}
        );
    }

    public @NotNull CompletableFuture<UpdateRecordResponse> updateRecordWithTemplateByAccountUuid(
            int recordId,
            int templateId,
            @NotNull UUID accountUuid,
            @NotNull Map<String, Object> replaceValues
    ) {
        return requestService.sendRequest(
                Methods.UPDATE_RECORD,
                Params.of(
                        "recordId", recordId,
                        "templateId", templateId,
                        "useDictionary", true,
                        "accountUuid", accountUuid,
                        "replaceValues", replaceValues
                ),
                new TypeToken<>() {}
        );
    }
}
